# Generated by Django 5.1.6 on 2025-03-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_teammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='description',
        ),
    ]
